feature CRA/2 :navbar menu plus logo
CodersCampLittleDevs/CodersCamp2021-ProjectSinglePageApplication-PetsAdoptAndCarePortal pull request #2
Opened 2022-01-14 13:40 UTC by WelcomeInFront

2022-01-14 14:09 UTC, JustD1d1t reviewed
Resize this image. It is used only for logo so it should be much smaller. Use paint for example to resize this. I think max 200x200px should be fine

2022-01-14 14:09 UTC, JustD1d1t commented on src/components/Navbar/MenuItems.js
> +    icon: <FaIcons.FaUserCog />,
where can i find library for those icons?

2022-01-14 14:09 UTC, JustD1d1t commented on src/components/Navbar/Navbar.js
> +// import * as FaIcons from "react-icons/fa";
Remove commented line

2022-01-14 14:09 UTC, JustD1d1t commented on src/components/Navbar/Navbar.module.scss
> +padding: 6px;
Styling. Once time "tab", next time "tab + space", another nothing

2022-01-14 14:09 UTC, JustD1d1t commented on src/components/Navbar/Navbar.module.scss
> +    &__logo {
same as above

2022-01-14 14:09 UTC, JustD1d1t commented on src/components/Navbar/Navbar.module.scss
> +  }
same as above

2022-01-14 14:09 UTC, JustD1d1t commented on src/components/Navbar/Navbar.module.scss
> +        }
same as above

2022-01-14 14:09 UTC, JustD1d1t commented on src/components/Navbar/Navbar.module.scss
> +   text-align:center;
same as above

2022-01-14 14:09 UTC, JustD1d1t commented on src/components/Navbar/Navbar.module.scss
> +
remove empty lines

2022-01-14 14:09 UTC, JustD1d1t commented on src/components/logo/Logo.jsx
> +  const { classX } = props;
change this wroking props name. I don't know what does it mean. Is it special class cause it's "X"?

2022-01-14 16:25 UTC, ruljin commented on src/components/Navbar/MenuItems.js
> +import * as FaIcons from "react-icons/fa";
The `package.json` file with `react-icons` as a dependency hasn't been added in any commits. Second, what is the point of importing the `whole` library into the file if you are using only those icons you need from it (`import { A, B, C } from 'react-icons/fa'`) and not the whole library (`... * as FaIcons from ...`).

2022-01-14 16:27 UTC, ruljin commented on src/components/Navbar/MenuItems.js
> +import React from "react";
There is no need to import the whole react library into the file from the newest version of it.

2022-01-14 16:30 UTC, ruljin commented on src/components/logo/Logo.jsx
> +  const { classX } = props;
Props validation check it up as missing. First of all why you don't destructure it when receiving it into the component?
`Logo = ({ classX }) => { ...`
Why just don't pass it for example as `classes`? I think it is more obvious and verbose that way.

2022-01-14 16:31 UTC, ruljin commented on src/components/logo/Logo.jsx
> +import logo from "./3.png";
The image should be moved to `/src/assets` and it should have an obvious name like for example `logo` or `logo__image`.

2022-01-14 16:33 UTC, ruljin commented on src/components/logo/Logo.jsx
> +  const { classX } = props;
From what I'm aware you are using in the project `CSS modules` so why there is a `logo.css` file in addition that is empty? Remove it if it is empty.

2022-01-14 16:36 UTC, ruljin commented on src/components/Navbar/MenuItems.js
> +export const MenuItems = [
I have a few suggestions here. First of all, the file should be called `MenuItem` and have `.jsx` format. In shortcut, it should be a component that has the code for a single menu list item component.

Second, the `MenuItems` constant should be called `MENU_ITEMS` and should be moved to the `Navbar` component.

2022-01-14 16:38 UTC, ruljin commented on src/components/Navbar/MenuItems.js
> +    url: "#",
As far as I know, you already have routing for most pages and even if some is missing, you could ask your team leader to answer you under what URL would be a certain page available to already set it.

2022-01-14 16:39 UTC, ruljin commented on src/components/Navbar/Navbar.js
> +import React from "react";
Same as before. There is no need to import the whole react library into the file from the newest version of it.

2022-01-14 16:39 UTC, ruljin commented on src/components/Navbar/Navbar.js
> +import styles from "./Navbar.module.scss";
If I'm correct the `CSS module` name convention is `component_name_without_uppercase.module.scss`.

2022-01-14 16:40 UTC, ruljin commented on src/components/Navbar/Navbar.js
> +// import * as FaIcons from "react-icons/fa";
Remove the comment.

2022-01-14 16:45 UTC, ruljin commented on src/components/Navbar/Navbar.js
> +        {MenuItems.map((item, inx) => {
Avoid using shortcuts in variable names. It makes code harder to read. So no `inx` but `index`.

2022-01-14 16:46 UTC, ruljin commented on src/components/Navbar/Navbar.js
> +function Navbar() {
As for me, it is better to use whenever it is possible a named export, not default.

2022-01-14 16:47 UTC, ruljin commented on src/components/Navbar/Navbar.js
> +      <ul className={styles.navbar__items}>
The list should be granulated (moved) to the `Menu` component.

2022-01-14 16:48 UTC, ruljin commented on src/components/Navbar/Navbar.js
> +      <div className={`${styles["navbar__logo-container"]}`}>
Why using string literal here?

2022-01-14 16:48 UTC, ruljin commented on src/components/Navbar/Navbar.js
> +      <div className={`${styles["navbar__logo-container"]}`}>
Why using string literal here?

2022-01-14 16:49 UTC, ruljin commented on src/components/Navbar/Navbar.js
> +function Navbar() {
As for me, it is better to use whenever it is possible a named export, not default.

2022-01-14 16:49 UTC, ruljin commented on src/components/Navbar/Navbar.js
> +      <div className={`${styles["navbar__logo-container"]}`}>
Why use a string literal here?

2022-01-14 16:49 UTC, ruljin commented on src/components/Navbar/Navbar.js
> +        <Logo classX={`${styles.navbar__logo}`} />
Why use a string literal here?

2022-01-14 17:14 UTC, ruljin commented on src/components/Navbar/Navbar.js
> +            <li keys={inx}>
Same as before. Avoid using shortcuts in variable names - `index` not `inx`.

2022-01-14 17:15 UTC, ruljin commented on src/components/Navbar/Navbar.module.scss
> +.navbar {
You have `prettier` configuration in the project. Why not format code using it?

2022-01-14 17:15 UTC, ruljin commented on src/components/Navbar/Navbar.module.scss
> +
Max and minimal one empty line of space between rules.

2022-01-14 17:15 UTC, ruljin commented on src/components/Navbar/Navbar.module.scss
> +
Max and minimal one empty line of space between rules.

2022-01-14 17:16 UTC, ruljin commented on src/components/Navbar/Navbar.module.scss
> +
Max and minimal one empty line of space between rules.

2022-01-14 17:16 UTC, ruljin commented on src/components/Navbar/Navbar.module.scss
> +
Max and minimal one empty line of space between rules.

2022-01-14 17:16 UTC, ruljin commented on src/components/Navbar/Navbar.module.scss
> +
Max and minimal one empty line of space between rules.

2022-01-14 17:16 UTC, ruljin commented on src/components/logo/Logo.jsx
> +const Logo = (props) => {
As for me, it is better to use whenever it is possible a named export, not default.

2022-01-14 17:18 UTC, ruljin requested changes
There is still some room for improvement.

2022-01-14 17:34 UTC, JustD1d1t commented on src/components/Navbar/Navbar.module.scss
> +    position: fixed;
i think it should be "sticky"

2022-01-19 15:36 UTC, ruljin commented on src/assets/logo/Logo.jsx
> +export const Logo = ({ classes }) => {
`Logo` **image file** should be in assets and it should be imported to the `Logo` **component file** which should be in components.

2022-01-19 15:42 UTC, ruljin commented on src/components/Navbar/MenuItem.jsx
> +  return { children };
What is the point of creating a **component** that the only thing it does is, display the same element it receives? It is the same as displaying it on the parent level but longer.

2022-01-19 15:43 UTC, ruljin requested changes
Changes requested.

2022-01-24 10:43 UTC, ruljin requested changes
Changes requested

2022-01-24 10:43 UTC, ruljin commented on src/components/Navbar/Menu.jsx
> +    <div className={styles[("navbar__logo-container", "menu")]}>
You can install and use `clsx`

2022-01-24 10:43 UTC, ruljin commented on src/components/Navbar/Menu.jsx
> +      {list.map((element) => {
Not `element` but `item` or `listItem`

2022-01-24 10:43 UTC, ruljin commented on src/components/Navbar/Menu.jsx
> +import propTypes from "prop-types";
Be consistent `PropTypes`

2022-01-24 10:43 UTC, ruljin commented on src/components/Navbar/Menu.jsx
> +import styles from "./Navbar.module.scss";
Module names from a lowercase

2022-01-24 10:43 UTC, ruljin commented on src/components/Navbar/Navbar.jsx
> +// import { useEffect, useState } from "react";
Remove it

2022-01-24 10:43 UTC, ruljin commented on src/components/Navbar/Navbar.jsx
> +import styles from "./Navbar.module.scss";
Module names from a lowercase

2022-01-24 10:43 UTC, ruljin commented on src/components/Navbar/Navbar.jsx
> +  <div className={styles.hamburger} id={styles.hamburger}>
Is there any reason for this `id` here?

2022-01-24 10:43 UTC, ruljin commented on src/components/Navbar/Navbar.jsx
> +  // commented for now cause it might be useful
Remove the whole comment `!!!`

2022-01-24 10:43 UTC, ruljin commented on src/components/Navbar/Navbar.module.scss
> +// .navbar {
REMOVE THE WHOLE COMMENT `!!!`

2022-01-24 10:43 UTC, ruljin commented on src/components/Navbar/Navbar.module.scss
> +//Hamburger styles
☝️

2022-01-24 10:43 UTC, ruljin commented on src/components/Navbar/Navbar.module.scss
> +  // display: none;
☝️

2022-01-24 10:43 UTC, ruljin commented on src/components/logo/Logo.jsx
> +import propTypes from "prop-types";
Be consistent - `PropTypes`

2022-01-24 10:43 UTC, ruljin commented on src/routes/index.js
> +// import { Announcement } from "../modules/announcements/pages/Announcement";
Remove it

2022-01-24 10:43 UTC, ruljin commented on src/routes/index.js
> +  // {
Remove it

2022-01-24 20:49 UTC, ruljin requested changes
Changed requested

2022-01-24 20:49 UTC, ruljin commented on src/components/Navbar/Navbar.module.scss
> +.navbar {
Git detect this file as `Navbar.module.scss` - wasn't it deleted?

2022-01-24 20:49 UTC, ruljin commented on src/components/logo/Logo.jsx
> +import logo from "./logo.png";
Move it to assets and import it from it

2022-02-02 09:51 UTC, ruljin requested changes
Changes requested

2022-02-02 09:51 UTC, ruljin commented on src/components/Navbar/Menu.jsx
> +    <div className={clsx([styles.navbar__logo_container, styles.menu])}>
There should be something like two or three containers on the menu. The `left` side and the `right` side. On the left side, there should be a logo and the navigation of the basic route. On the right side, there should be login and register URLs.

2022-02-02 09:51 UTC, ruljin commented on src/routes/index.js
>  export const routes = [
The URLs titles are other on the design than in the routes.

2022-02-02 09:51 UTC, ruljin commented on src/components/Navbar/Navbar.module.scss
> +.navbar {
Navbar styles are still detected as `navbar.module.scss`. It shouldn't exist anymore and the `navbar.module.scss` file should be detected. Besides, the styles for the desktop `Navbar` are not proper. The height is different, routes placement and padding between elements and from the page sides.

2022-02-02 09:51 UTC, ruljin commented on src/components/Navbar/Navbar.module.scss
> +#hamburger {
I think that even for the mobile the whole `Navbar` shouldn't disappear. The only change should generate a `Navbar` with the logo on the left and with the hamburger icon (button) on the right, which opens and close the mobile menu.

2022-02-07 18:16 UTC, ruljin requested changes
Changes requested

2022-02-07 18:16 UTC, ruljin commented on src/components/Navbar/Navbar.jsx
> +      className={isOpen ? hamburgerClasses : styles.hamburger}
Why not pass here only `hamburgerClasses`? You have `clsx` that manipulate styles depending on props value.

2022-02-08 16:56 UTC, merged